CREATE DATABASE livr_ar;
USE livr_ar;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    cnpj VARCHAR(30) DEFAULT NULL UNIQUE,
    tipo VARCHAR(30) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    telefone VARCHAR(30) DEFAULT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM usuarios;
